-- Таблица цветов
CREATE TABLE FLOWERS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    flower TEXT NOT NULL,
    sort TEXT NOT NULL,
    price DECIMAL(10,2) NOT NULL
);

-- Таблица названий композиций
CREATE TABLE KOMPOS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

-- Таблица состава (связи)
CREATE TABLE KOMPOS_IN (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    FLOWERS_id INTEGER NOT NULL,
    KOMPOS_id INTEGER NOT NULL,
    count INTEGER NOT NULL,
    FOREIGN KEY (FLOWERS_id) REFERENCES FLOWERS (id),
    FOREIGN KEY (KOMPOS_id) REFERENCES KOMPOS (id)
);

-- Таблица заказов
CREATE TABLE "ORDER" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    KOMPOS_id INTEGER NOT NULL,
    customer TEXT NOT NULL,
    date_get DATE NOT NULL,
    date_set DATE NOT NULL,
    count INTEGER NOT NULL,
    FOREIGN KEY (KOMPOS_id) REFERENCES KOMPOS (id)
);
