name: Build App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install libsqlite3-dev
      - name: Compile
        run: g++ -Iincludes src/main.cpp src/database.cpp -lsqlite3 -o bin/app
